{
	"version": 1484514701,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/intro-sheet0.png",
		"images/tiledbackground.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/tilemap.png",
		"images/tiledbackground2.png",
		"images/canoe-sheet0.png",
		"images/tonguetip-sheet0.png",
		"images/tiledbackground3.png",
		"images/sprite2-sheet0.png",
		"images/limitelateral-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/chewedenemy-sheet0.png",
		"images/sprite-sheet0.png",
		"images/hudlifeicon-sheet0.png",
		"images/hud_x_icon-sheet0.png",
		"images/water-sheet0.png",
		"images/boss-sheet0.png",
		"images/layoutlimits-sheet0.png",
		"images/tilemap2.png",
		"images/lifeup-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite7-sheet0.png",
		"media/cobragrande_explosion.m4a",
		"media/cobragrande_explosion.ogg",
		"media/frog_dead.m4a",
		"media/frog_dead.ogg",
		"media/frog_jump.m4a",
		"media/frog_jump.ogg",
		"media/frog_landing.m4a",
		"media/frog_landing.ogg",
		"media/frog_attack.m4a",
		"media/frog_attack.ogg",
		"media/cobragrande_hit.ogg",
		"media/enemies_explosion.ogg",
		"media/life_up.m4a",
		"media/life_up.ogg",
		"media/chee zee jungle.m4a",
		"media/chee zee jungle.ogg",
		"media/volatile reaction.m4a",
		"media/volatile reaction.ogg",
		"media/game over screen.ogg",
		"media/intro screen.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}