{
	"version": 1480135578,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/background-sheet0.png",
		"images/bricks-sheet0.png",
		"images/bricks-sheet1.png",
		"images/hat-sheet0.png",
		"images/tortilla-sheet0.png",
		"images/borders-sheet0.png",
		"images/soldier-sheet0.png",
		"images/bullet-sheet0.png",
		"images/trump-sheet0.png",
		"images/tequila-sheet0.png",
		"images/destroyer-sheet0.png",
		"images/snake-sheet0.png",
		"images/mexican-sheet0.png",
		"images/mexican-sheet1.png",
		"images/soldier_skin-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/defeat_audio.m4a",
		"media/defeat_audio.ogg",
		"media/pepper_powerup.m4a",
		"media/pepper_powerup.ogg",
		"media/soldier_destroy.m4a",
		"media/soldier_destroy.ogg",
		"media/tequila_powerup.m4a",
		"media/tortilla_bounce.m4a",
		"media/tortilla_bounce.ogg",
		"media/victory_audio.m4a",
		"media/victory_audio.ogg",
		"media/tequila_powerup.ogg",
		"media/carnivale intrigue - music.m4a",
		"media/carnivale intrigue - music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}